redisHost: localhost:6379
mqtt:
  host: "192.168.178.33:1883"
scriptRunner:
  path: "./test_scripts"

monitors:
  - name: "test"
    friendlyName: "Monitor 1"
    reportTimeout: 1m
    mqtt:
      topic: "monitors/test"
      upMessage: "UP"
      downMessage: "DOWN"

  - name: "test2"
    friendlyName: "Monitor 2"
    scriptRunner:
      script: "fail.sh"
      interval: "10s"

  - name: "test3"
    friendlyName: "Monitor 3"
    scriptRunner:
      script: "success.sh"
      interval: "10s"

  - name: "script_with_args"
    friendlyName: "Monitor 3"
    ntfyUrl: "https://ntfy.sh/aui4u92w34iwebfui9owergh02t89"
    scriptRunner:
      script: "script_with_args.sh"
      args:
        - "hallo"
        - "test"
      interval: "10s"

  - name: "test4"
    friendlyName: "Monitor 3"

  - name: "testre"
    friendlyName: "Monitor 1"
