redisHost: localhost:6379
mqtt:
  host: "192.168.178.33:1883"

monitors:
  - name: "test"
    friendlyName: "Monitor 1"
    reportTimeout: 1m
    mqtt:
      topic: "monitors/test"
      upMessage: "UP"
      downMessage: "DOWN"

  - name: "test2"
    friendlyName: "Monitor 2"

  - name: "test3"
    friendlyName: "Monitor 3"

  - name: "test4"
    friendlyName: "Monitor 3"

  - name: "testre"
    friendlyName: "Monitor 1"
